spring.application.name=agile-agent
langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY:demo}
langchain4j.open-ai.chat-model.model-name=gpt-4o
langchain4j.open-ai.chat-model.temperature=0.0
jira.url=https://stefanini-spike.atlassian.net
jira.username=aerl@cesar.school
jira.token=${JIRA_API_KEY:demo}
jira.project-key=SCRUM